name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Configure machine
      run: |
        sudo apt-get update -qq
        sudo apt-get install ninja-build cmake g++-10 clang

    - name: Configure build
      run: |
        mkdir build.tmp && cd build.tmp
        cmake .. -G ninja-build -DSKIP_BUILD_TEST=ON

    - name: Perform build
      run: ninja
